### ISSUE TITLE
Milestone cleanup (v0.1)

### ISSUE THREAD

**Issue by csabe812** [csabe812/SpringIsHereEnterprise#17]
What need to be worked:
- [ ] registration
- [ ] user login
- [ ] admin login
- [ ] logout
- [ ] shop list
- [ ] new shop
- [ ] edit shop
- [ ] product list by shop
- [ ] new product
- [ ] edit product
- [ ] exception/error/other pages fragment, decorator
- [ ] writing tests to them
